name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag rpgruss/docker-influxdb-grafana:latest
    - name: Push the Docker image
      run: docker push rpgruss/docker-influxdb-grafana:latest

